### ISSUE TITLE
Code-Along set up instructions

### ISSUE THREAD

**Issue by joemilius** [learn-co-curriculum/python-p3-migrations-and-alembic#17] opened 2023-01-18 17:02 UTC
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195260?module_item_id=439018

### Concern

In the set up instructions it says to create a lib file then run alembic init migrations after cding into the lib directory.  It seems that for alembic to work it needs to be installed in that lab with pip install alembic.  It seems that running the installation command before even creating the lib file would make sure that students have what they need for the lab to work as intended.  

### Suggested Changes

Just adding the pip install alembic command to the set up instructions would suffice. (Maybe a brief explanation of why alembic needs to be installed)

**Comment by professor-ben** [comment] 2023-01-20 19:30
Hey Joe,

I just tried this out and wasn't able to reproduce the error. Could you try again and make sure you're exiting any old `pipenvs` before running `pipenv shell` in this repo? If you get the error again, please post a screenshot or copy the error message.

Thanks,
Ben

**Comment by professor-ben** [comment] 2023-02-21 22:29
I'm closing this because our team has not been able to reproduce it, but please reopen if this pops up again.

**Comment by sheenasany** [comment] 2023-03-01 19:03
I think the issue is that students may need to be reminded to run `pipenv install` && `pipenv shell` in order to run the migrations using the `alembic init migrations` command. 

I did not run those commands prior to the migrations and I was getting an error saying that 
`Command 'alembic' not found, but can be installed with:

sudo apt install alembic`

This might clear up any confusion in the future for students who are trying to get through this lab. 
Here's an example of what was happening for me as I was trying to test this out for myself.

![image](https://user-images.githubusercontent.com/105241920/222238819-ad0a2ae1-394e-4dad-a72b-f97614dda089.png)

**Comment by professor-ben** [comment] 2023-03-07 00:28
Got it. The instructions to enter their Pipenv have been added in.

**Closed as completed** 2023-03-07 00:28 UTC
Labels: se curriculum, se python
